export const LANGUAGES = [
  {"alias": "accesslog", "name": "Access logs"},
  {"alias": "ada", "name": "Ada"},
  {"alias": "actionscript", "name": "ActionScript"},
  {"alias": "apache", "name": "Apache"},
  {"alias": "applescript", "name": "AppleScript"},
  {"alias": "asciidoc", "name": "AsciiDoc"},
  {"alias": "awk", "name": "Awk"},
  {"alias": "bash", "name": "Bash"},
  {"alias": "basic", "name": "Basic"},
  {"alias": "cpp", "name": "C++"},
  {"alias": "clojure", "name": "Clojure"},
  {"alias": "coffeescript", "name": "CoffeeScript"},
  {"alias": "dos", "name": "DOS"},
  {"alias": "dart", "name": "Dart"},
  {"alias": "delphi", "name": "Delphi"},
  {"alias": "diff", "name": "Diff"},
  {"alias": "dockerfile", "name": "Dockerfile"},
  {"alias": "erlang", "name": "Erlang"},
  {"alias": "go", "name": "Go"},
  {"alias": "gradle", "name": "Gradle"},
  {"alias": "groovy", "name": "Groovy"},
  {"alias": "xml", "name": "HTML, XML"},
  {"alias": "http", "name": "HTTP"},
  {"alias": "haskell", "name": "Haskell"},
  {"alias": "ini", "name": "Ini"},
  {"alias": "json", "name": "JSON"},
  {"alias": "java", "name": "Java"},
  {"alias": "javascript", "name": "JavaScript"},
  {"alias": "lisp", "name": "Lisp"},
  {"alias": "lua", "name": "Lua"},
  {"alias": "makefile", "name": "Makefile"},
  {"alias": "markdown", "name": "Markdown"},
  {"alias": "nginx", "name": "Nginx"},
  {"alias": "ocaml", "name": "OCaml"},
  {"alias": "objectivec", "name": "Objective C"},
  {"alias": "php", "name": "PHP"},
  {"alias": "perl", "name": "Perl"},
  {"alias": "powershell", "name": "PowerShell"},
  {"alias": "prolog", "name": "Prolog"},
  {"alias": "protobuf", "name": "Protocol Buffers"},
  {"alias": "puppet", "name": "Puppet"},
  {"alias": "python", "name": "Python"},
  {"alias": "r", "name": "R"},
  {"alias": "ruby", "name": "Ruby"},
  {"alias": "rust", "name": "Rust"},
  {"alias": "scss", "name": "SCSS"},
  {"alias": "sql", "name": "SQL"},
  {"alias": "scala", "name": "Scala"},
  {"alias": "scheme", "name": "Scheme"},
  {"alias": "smalltalk", "name": "Smalltalk"},
  {"alias": "stylus", "name": "Stylus"},
  {"alias": "swift", "name": "Swift"},
  {"alias": "tcl", "name": "Tcl"},
  {"alias": "thrift", "name": "Thrift"},
  {"alias": "typescript", "name": "TypeScript"},
  {"alias": "vbnet", "name": "VB.Net"},
  {"alias": "vbscript", "name": "VBScript"},
  {"alias": "vhdl", "name": "VHDL"},
  {"alias": "vim", "name": "Vim Script"},
  {"alias": "x86asm", "name": "x86 Assembly"}
];
