export const LANGUAGES = [
  {"value": "accesslog", "text": "Access logs"},
  {"value": "ada", "text": "Ada"},
  {"value": "actionscript", "text": "ActionScript"},
  {"value": "apache", "text": "Apache"},
  {"value": "applescript", "text": "AppleScript"},
  {"value": "asciidoc", "text": "AsciiDoc"},
  {"value": "awk", "text": "Awk"},
  {"value": "bash", "text": "Bash"},
  {"value": "basic", "text": "Basic"},
  {"value": "cpp", "text": "C++"},
  {"value": "clojure", "text": "Clojure"},
  {"value": "coffeescript", "text": "CoffeeScript"},
  {"value": "dos", "text": "DOS"},
  {"value": "dart", "text": "Dart"},
  {"value": "delphi", "text": "Delphi"},
  {"value": "diff", "text": "Diff"},
  {"value": "dockerfile", "text": "Dockerfile"},
  {"value": "erlang", "text": "Erlang"},
  {"value": "go", "text": "Go"},
  {"value": "gradle", "text": "Gradle"},
  {"value": "groovy", "text": "Groovy"},
  {"value": "xml", "text": "HTML, XML"},
  {"value": "http", "text": "HTTP"},
  {"value": "haskell", "text": "Haskell"},
  {"value": "ini", "text": "Ini"},
  {"value": "json", "text": "JSON"},
  {"value": "java", "text": "Java"},
  {"value": "javascript", "text": "JavaScript"},
  {"value": "lisp", "text": "Lisp"},
  {"value": "lua", "text": "Lua"},
  {"value": "makefile", "text": "Makefile"},
  {"value": "markdown", "text": "Markdown"},
  {"value": "nginx", "text": "Nginx"},
  {"value": "ocaml", "text": "OCaml"},
  {"value": "objectivec", "text": "Objective C"},
  {"value": "php", "text": "PHP"},
  {"value": "perl", "text": "Perl"},
  {"value": "powershell", "text": "PowerShell"},
  {"value": "prolog", "text": "Prolog"},
  {"value": "protobuf", "text": "Protocol Buffers"},
  {"value": "puppet", "text": "Puppet"},
  {"value": "python", "text": "Python"},
  {"value": "r", "text": "R"},
  {"value": "ruby", "text": "Ruby"},
  {"value": "rust", "text": "Rust"},
  {"value": "scss", "text": "SCSS"},
  {"value": "sql", "text": "SQL"},
  {"value": "scala", "text": "Scala"},
  {"value": "scheme", "text": "Scheme"},
  {"value": "smalltalk", "text": "Smalltalk"},
  {"value": "stylus", "text": "Stylus"},
  {"value": "swift", "text": "Swift"},
  {"value": "tcl", "text": "Tcl"},
  {"value": "thrift", "text": "Thrift"},
  {"value": "typescript", "text": "TypeScript"},
  {"value": "vbnet", "text": "VB.Net"},
  {"value": "vbscript", "text": "VBScript"},
  {"value": "vhdl", "text": "VHDL"},
  {"value": "vim", "text": "Vim Script"},
  {"value": "x86asm", "text": "x86 Assembly"}
];
